import { AchievementCatalogRecord, ChallengeProgressRecord, ChallengeRecord, UserAchievementRecord, UserProfileRecord } from './contracts';

const levelForPoints = (points: number) => 1 + Math.floor(points / 250);
const nextLevelPointsForPoints = (points: number) => levelForPoints(points) * 250;
const iso = (value: string) => new Date(value).toISOString();

function userSeed(input: {
  uid: string;
  name: string;
  email: string;
  initials: string;
  points: number;
  completed: number;
  bestStreak: number;
  currentStreak: number;
  badges: number;
  lastCompletedDate?: string | null;
  avatarPath?: string | null;
}): UserProfileRecord {
  return {
    uid: input.uid,
    name: input.name,
    email: input.email,
    initials: input.initials,
    points: input.points,
    level: levelForPoints(input.points),
    nextLevelPoints: nextLevelPointsForPoints(input.points),
    completed: input.completed,
    bestStreak: input.bestStreak,
    currentStreak: input.currentStreak,
    badges: input.badges,
    avatarPath: input.avatarPath ?? null,
    lastCompletedDate: input.lastCompletedDate ? iso(input.lastCompletedDate) : null,
    updatedAt: new Date().toISOString(),
  };
}

export const demoAchievementCatalog: AchievementCatalogRecord[] = [
  {
    id: 'first_challenge',
    title: 'First Steps',
    subtitle: 'Complete your first challenge',
    icon: '🏆',
    rewardPoints: 50,
    total: 1,
    sortOrder: 1,
  },
  {
    id: 'five_challenges',
    title: 'Challenge Seeker',
    subtitle: 'Complete 5 challenges',
    icon: '🎯',
    rewardPoints: 120,
    total: 5,
    sortOrder: 2,
  },
  {
    id: 'first_nature',
    title: 'Nature Explorer',
    subtitle: 'Complete your first nature challenge',
    icon: '🌲',
    rewardPoints: 40,
    total: 1,
    sortOrder: 3,
  },
  {
    id: 'first_cultural',
    title: 'Culture Lover',
    subtitle: 'Complete your first cultural challenge',
    icon: '🏛️',
    rewardPoints: 40,
    total: 1,
    sortOrder: 4,
  },
  {
    id: 'first_historical',
    title: 'History Hunter',
    subtitle: 'Complete your first historical challenge',
    icon: '🏰',
    rewardPoints: 40,
    total: 1,
    sortOrder: 5,
  },
  {
    id: 'first_adventure',
    title: 'Adventure Awaits',
    subtitle: 'Complete your first adventure challenge',
    icon: '⛰️',
    rewardPoints: 40,
    total: 1,
    sortOrder: 6,
  },
  {
    id: 'three_day_streak',
    title: 'Streak Starter',
    subtitle: 'Reach a 3-day streak',
    icon: '🔥',
    rewardPoints: 80,
    total: 3,
    sortOrder: 7,
  },
];

export const demoChallenges: ChallengeRecord[] = [
  {
    id: 'test-tu-sofia',
    title: 'Check In at TU Sofia',
    location: 'Technical University of Sofia',
    description: 'Test challenge at the main Technical University of Sofia campus on 8 St. Kliment Ohridski Blvd.',
    imageAsset: 'assets/Image-Alexander-Nevsky-Cathedral@2x.png',
    distanceKm: 0.4,
    points: 320,
    duration: '20-30 minutes',
    difficulty: 'hard',
    category: 'Cultural',
    latitude: 42.6543,
    longitude: 23.3533,
    explorersCompleted: 87,
  },
  {
    id: 'test-sopharma-business-towers',
    title: 'Check In at Sopharma Business Towers',
    location: 'Sopharma Business Towers',
    description: 'Test challenge at Sopharma Business Towers, 5 Lachezar Stanchev St., Sofia.',
    imageAsset: 'assets/Image-Old-Town-Plovdiv@2x.png',
    distanceKm: 0.6,
    points: 220,
    duration: '15-20 minutes',
    difficulty: 'medium',
    category: 'Cultural',
    latitude: 42.665324,
    longitude: 23.35589,
    explorersCompleted: 54,
  },
  {
    id: 'test-inergy-borovo',
    title: 'Check In at Inergy Fitness Borovo',
    location: 'Inergy Fitness & Spa, Borovo',
    description: 'Test challenge at Inergy Fitness & Spa in Borovo, Sofia, at 59 Solun St.',
    imageAsset: 'assets/Image-Belogradchik-Rocks@2x.png',
    distanceKm: 0.2,
    points: 140,
    duration: '10-15 minutes',
    difficulty: 'easy',
    category: 'Adventure',
    latitude: 42.6686257,
    longitude: 23.2882313,
    explorersCompleted: 39,
  },
  {
    id: 'cultural-rila-monastery',
    title: 'Discover Rila Monastery',
    location: 'Rila Mountains',
    description: 'Explore Bulgaria’s most iconic monastery and photograph its colorful courtyard frescoes.',
    imageAsset: 'assets/Image-Discover-Rila-Monastery@2x.png',
    distanceKm: 2.3,
    points: 260,
    duration: '2-3 hours',
    difficulty: 'medium',
    category: 'Cultural',
    latitude: 42.1333,
    longitude: 23.3400,
    explorersCompleted: 1247,
  },
  {
    id: 'cultural-old-town-plovdiv',
    title: 'Old Town Plovdiv',
    location: 'Plovdiv',
    description: 'Walk the Revival-era lanes of Old Town Plovdiv and capture its colorful facades.',
    imageAsset: 'assets/Image-Old-Town-Plovdiv@2x.png',
    distanceKm: 1.2,
    points: 140,
    duration: '1-2 hours',
    difficulty: 'easy',
    category: 'Cultural',
    latitude: 42.1460,
    longitude: 24.7516,
    explorersCompleted: 830,
  },
  {
    id: 'cultural-nevsky-cathedral',
    title: 'Alexander Nevsky Cathedral',
    location: 'Sofia',
    description: 'Visit Sofia’s golden-domed cathedral and capture its monumental facade.',
    imageAsset: 'assets/Image-Alexander-Nevsky-Cathedral@2x.png',
    distanceKm: 0.5,
    points: 180,
    duration: '30-45 minutes',
    difficulty: 'easy',
    category: 'Cultural',
    latitude: 42.6958,
    longitude: 23.3329,
    explorersCompleted: 980,
  },
  {
    id: 'cultural-koprivshtitsa-houses',
    title: 'Koprivshtitsa Revival Houses',
    location: 'Koprivshtitsa',
    description: 'Discover the painted houses and heroic history of Koprivshtitsa.',
    imageAsset: 'assets/Image-Old-Town-Plovdiv@2x.png',
    distanceKm: 4.4,
    points: 300,
    duration: '2-3 hours',
    difficulty: 'hard',
    category: 'Cultural',
    latitude: 42.6370,
    longitude: 24.3574,
    explorersCompleted: 441,
  },
  {
    id: 'cultural-etar-museum',
    title: 'Etar Open-Air Museum',
    location: 'Gabrovo',
    description: 'See living crafts demonstrations in the historic Etar village museum.',
    imageAsset: 'assets/Image-Discover-Rila-Monastery@2x.png',
    distanceKm: 3.1,
    points: 220,
    duration: '1.5-2 hours',
    difficulty: 'medium',
    category: 'Cultural',
    latitude: 42.8063,
    longitude: 25.3461,
    explorersCompleted: 612,
  },
  {
    id: 'nature-belogradchik-rocks',
    title: 'Belogradchik Rocks',
    location: 'Belogradchik',
    description: 'Hike to the dramatic sandstone towers and explore the fortress viewpoints.',
    imageAsset: 'assets/Image-Belogradchik-Rocks@2x.png',
    distanceKm: 5.7,
    points: 280,
    duration: '3-4 hours',
    difficulty: 'hard',
    category: 'Nature',
    latitude: 43.6231,
    longitude: 22.6833,
    explorersCompleted: 416,
  },
  {
    id: 'nature-seven-rila-lakes',
    title: 'Seven Rila Lakes',
    location: 'Rila National Park',
    description: 'Complete the alpine trail linking the most famous glacial lakes in Bulgaria.',
    imageAsset: 'assets/Image-Discover-Rila-Monastery@2x.png',
    distanceKm: 7.8,
    points: 420,
    duration: '4-5 hours',
    difficulty: 'hard',
    category: 'Nature',
    latitude: 42.2104,
    longitude: 23.3125,
    explorersCompleted: 702,
  },
  {
    id: 'nature-krushuna-waterfalls',
    title: 'Krushuna Waterfalls',
    location: 'Krushuna',
    description: 'Walk the turquoise cascades and wooden bridges at Krushuna.',
    imageAsset: 'assets/Image-Belogradchik-Rocks@2x.png',
    distanceKm: 2.1,
    points: 170,
    duration: '1 hour',
    difficulty: 'easy',
    category: 'Nature',
    latitude: 43.2450,
    longitude: 24.5547,
    explorersCompleted: 911,
  },
  {
    id: 'nature-devetashka-cave',
    title: 'Devetashka Cave',
    location: 'Lovech Region',
    description: 'Explore the huge vaulted cave chamber and its natural skylights.',
    imageAsset: 'assets/Image-Belogradchik-Rocks@2x.png',
    distanceKm: 3.6,
    points: 260,
    duration: '2 hours',
    difficulty: 'medium',
    category: 'Nature',
    latitude: 43.2424,
    longitude: 24.8912,
    explorersCompleted: 587,
  },
  {
    id: 'nature-pirin-viewpoint',
    title: 'Pirin Panorama Viewpoint',
    location: 'Bansko',
    description: 'Reach a panoramic overlook with sweeping views over the Pirin peaks.',
    imageAsset: 'assets/Image-Discover-Rila-Monastery@2x.png',
    distanceKm: 4.8,
    points: 230,
    duration: '2-3 hours',
    difficulty: 'medium',
    category: 'Nature',
    latitude: 41.8357,
    longitude: 23.4842,
    explorersCompleted: 365,
  },
  {
    id: 'historical-tsarevets',
    title: 'Tsarevets Fortress',
    location: 'Veliko Tarnovo',
    description: 'Walk the medieval stronghold and trace the history of the Second Bulgarian Empire.',
    imageAsset: 'assets/Image-Tsarevets-Fortress@2x.png',
    distanceKm: 3.8,
    points: 220,
    duration: '2 hours',
    difficulty: 'medium',
    category: 'Historical',
    latitude: 43.0839,
    longitude: 25.6521,
    explorersCompleted: 720,
  },
  {
    id: 'historical-perperikon',
    title: 'Perperikon Sanctuary',
    location: 'Kardzhali',
    description: 'Climb to the ancient Thracian rock city and explore its carved chambers.',
    imageAsset: 'assets/Image-Tsarevets-Fortress@2x.png',
    distanceKm: 6.2,
    points: 360,
    duration: '3-4 hours',
    difficulty: 'hard',
    category: 'Historical',
    latitude: 41.7407,
    longitude: 25.4670,
    explorersCompleted: 388,
  },
  {
    id: 'historical-pliska',
    title: 'Great Basilica of Pliska',
    location: 'Pliska',
    description: 'Explore the ruins of the early Bulgarian capital and its monumental basilica.',
    imageAsset: 'assets/Image-Tsarevets-Fortress@2x.png',
    distanceKm: 2.7,
    points: 180,
    duration: '1-2 hours',
    difficulty: 'easy',
    category: 'Historical',
    latitude: 43.3639,
    longitude: 27.1215,
    explorersCompleted: 432,
  },
  {
    id: 'historical-madara-rider',
    title: 'Madara Rider Trail',
    location: 'Madara',
    description: 'See the UNESCO-listed Madara Rider carved high in the cliffs.',
    imageAsset: 'assets/Image-Tsarevets-Fortress@2x.png',
    distanceKm: 2.2,
    points: 150,
    duration: '1 hour',
    difficulty: 'easy',
    category: 'Historical',
    latitude: 43.2762,
    longitude: 27.1208,
    explorersCompleted: 664,
  },
  {
    id: 'historical-nessebar-walls',
    title: 'Nessebar Ancient Walls',
    location: 'Nessebar',
    description: 'Follow the fortified old town walls and Byzantine churches in Nessebar.',
    imageAsset: 'assets/Image-Alexander-Nevsky-Cathedral@2x.png',
    distanceKm: 1.0,
    points: 210,
    duration: '1.5 hours',
    difficulty: 'medium',
    category: 'Historical',
    latitude: 42.6582,
    longitude: 27.7362,
    explorersCompleted: 1054,
  },
  {
    id: 'adventure-vitosha-black-peak',
    title: 'Vitosha Black Peak Push',
    location: 'Vitosha',
    description: 'Take on Sofia’s classic summit route and capture the city panorama from above.',
    imageAsset: 'assets/Image-Belogradchik-Rocks@2x.png',
    distanceKm: 8.5,
    points: 400,
    duration: '4-5 hours',
    difficulty: 'hard',
    category: 'Adventure',
    latitude: 42.5612,
    longitude: 23.2789,
    explorersCompleted: 512,
  },
  {
    id: 'adventure-lakatnik-cliffs',
    title: 'Lakatnik Cliff Traverse',
    location: 'Iskar Gorge',
    description: 'Follow the ridge path above the Iskar Gorge and reach the panoramic ledges.',
    imageAsset: 'assets/Image-Belogradchik-Rocks@2x.png',
    distanceKm: 5.1,
    points: 310,
    duration: '3 hours',
    difficulty: 'hard',
    category: 'Adventure',
    latitude: 43.0868,
    longitude: 23.3854,
    explorersCompleted: 294,
  },
  {
    id: 'adventure-buzludzha-loop',
    title: 'Buzludzha Ridge Loop',
    location: 'Shipka',
    description: 'Hike the windy ridge route to the iconic Buzludzha monument.',
    imageAsset: 'assets/Image-Tsarevets-Fortress@2x.png',
    distanceKm: 4.4,
    points: 260,
    duration: '2-3 hours',
    difficulty: 'medium',
    category: 'Adventure',
    latitude: 42.7336,
    longitude: 25.3902,
    explorersCompleted: 603,
  },
  {
    id: 'adventure-rhodope-bike',
    title: 'Rhodope Bike Sprint',
    location: 'Smolyan Lakes',
    description: 'Complete a scenic mountain bike circuit around the Smolyan lakes area.',
    imageAsset: 'assets/Image-Discover-Rila-Monastery@2x.png',
    distanceKm: 6.0,
    points: 240,
    duration: '2 hours',
    difficulty: 'medium',
    category: 'Adventure',
    latitude: 41.6302,
    longitude: 24.6802,
    explorersCompleted: 351,
  },
  {
    id: 'adventure-kamen-del-walk',
    title: 'Kamen Del Sunrise Walk',
    location: 'Vitosha',
    description: 'Take the short sunrise route to Kamen Del for Sofia skyline views.',
    imageAsset: 'assets/Image-Discover-Rila-Monastery@2x.png',
    distanceKm: 1.9,
    points: 130,
    duration: '45 minutes',
    difficulty: 'easy',
    category: 'Adventure',
    latitude: 42.6486,
    longitude: 23.2914,
    explorersCompleted: 721,
  },
];

export const demoUsers: UserProfileRecord[] = [
  userSeed({
    uid: 'maria-ivanova',
    name: 'Maria Ivanova',
    email: 'maria.ivanova@example.com',
    initials: 'MI',
    points: 3320,
    completed: 13,
    bestStreak: 8,
    currentStreak: 4,
    badges: 7,
    lastCompletedDate: '2026-04-15T09:00:00Z',
  }),
  userSeed({
    uid: 'stefan-dimitrov',
    name: 'Stefan Dimitrov',
    email: 'stefan.dimitrov@example.com',
    initials: 'SD',
    points: 2840,
    completed: 11,
    bestStreak: 6,
    currentStreak: 2,
    badges: 6,
    lastCompletedDate: '2026-04-14T11:00:00Z',
  }),
  userSeed({
    uid: 'elena-georgieva',
    name: 'Elena Georgieva',
    email: 'elena.georgieva@example.com',
    initials: 'EG',
    points: 2310,
    completed: 9,
    bestStreak: 5,
    currentStreak: 1,
    badges: 5,
    lastCompletedDate: '2026-04-13T12:00:00Z',
  }),
  userSeed({
    uid: 'boris-petkov',
    name: 'Boris Petkov',
    email: 'boris.petkov@example.com',
    initials: 'BP',
    points: 1980,
    completed: 8,
    bestStreak: 5,
    currentStreak: 2,
    badges: 5,
    lastCompletedDate: '2026-04-15T07:00:00Z',
  }),
  userSeed({
    uid: 'demo-alex',
    name: 'Alex Petrov',
    email: 'alex.petrov@example.com',
    initials: 'AP',
    points: 1540,
    completed: 6,
    bestStreak: 7,
    currentStreak: 3,
    badges: 7,
    lastCompletedDate: '2026-04-15T08:30:00Z',
  }),
  userSeed({
    uid: 'diana-koleva',
    name: 'Diana Koleva',
    email: 'diana.koleva@example.com',
    initials: 'DK',
    points: 1290,
    completed: 5,
    bestStreak: 3,
    currentStreak: 1,
    badges: 4,
    lastCompletedDate: '2026-04-12T10:00:00Z',
  }),
  userSeed({
    uid: 'nikolai-stoyanov',
    name: 'Nikolai Stoyanov',
    email: 'nikolai.stoyanov@example.com',
    initials: 'NS',
    points: 1120,
    completed: 4,
    bestStreak: 2,
    currentStreak: 1,
    badges: 3,
    lastCompletedDate: '2026-04-11T10:00:00Z',
  }),
  userSeed({
    uid: 'svetlana-koleva',
    name: 'Svetlana Koleva',
    email: 'svetlana.koleva@example.com',
    initials: 'SK',
    points: 860,
    completed: 3,
    bestStreak: 2,
    currentStreak: 0,
    badges: 2,
    lastCompletedDate: '2026-04-09T10:00:00Z',
  }),
];

export const demoChallengeProgress: ChallengeProgressRecord[] = [
  {
    uid: 'demo-alex',
    challengeId: 'cultural-nevsky-cathedral',
    status: 'completed',
    startedAt: iso('2026-04-08T08:00:00Z'),
    completedAt: iso('2026-04-08T09:00:00Z'),
    proofPath: null,
    lastRouteShownAt: iso('2026-04-08T08:15:00Z'),
  },
  {
    uid: 'demo-alex',
    challengeId: 'cultural-old-town-plovdiv',
    status: 'completed',
    startedAt: iso('2026-04-09T08:00:00Z'),
    completedAt: iso('2026-04-09T10:00:00Z'),
    proofPath: null,
    lastRouteShownAt: iso('2026-04-09T08:25:00Z'),
  },
  {
    uid: 'demo-alex',
    challengeId: 'historical-tsarevets',
    status: 'completed',
    startedAt: iso('2026-04-10T08:00:00Z'),
    completedAt: iso('2026-04-10T11:00:00Z'),
    proofPath: null,
    lastRouteShownAt: iso('2026-04-10T08:20:00Z'),
  },
  {
    uid: 'demo-alex',
    challengeId: 'nature-belogradchik-rocks',
    status: 'completed',
    startedAt: iso('2026-04-11T08:00:00Z'),
    completedAt: iso('2026-04-11T12:00:00Z'),
    proofPath: null,
    lastRouteShownAt: iso('2026-04-11T08:20:00Z'),
  },
  {
    uid: 'demo-alex',
    challengeId: 'nature-devetashka-cave',
    status: 'completed',
    startedAt: iso('2026-04-12T08:00:00Z'),
    completedAt: iso('2026-04-12T10:00:00Z'),
    proofPath: null,
    lastRouteShownAt: iso('2026-04-12T08:10:00Z'),
  },
  {
    uid: 'demo-alex',
    challengeId: 'adventure-vitosha-black-peak',
    status: 'completed',
    startedAt: iso('2026-04-15T04:45:00Z'),
    completedAt: iso('2026-04-15T09:30:00Z'),
    proofPath: null,
    lastRouteShownAt: iso('2026-04-15T05:00:00Z'),
  },
  {
    uid: 'demo-alex',
    challengeId: 'historical-perperikon',
    status: 'active',
    startedAt: iso('2026-04-16T07:30:00Z'),
    completedAt: null,
    proofPath: null,
    lastRouteShownAt: iso('2026-04-16T07:35:00Z'),
  },
];

export const demoUserAchievements: UserAchievementRecord[] = demoAchievementCatalog.map((achievement, index) => ({
  uid: 'demo-alex',
  achievementId: achievement.id,
  unlockedAt: iso(`2026-04-${String(8 + index).padStart(2, '0')}T10:00:00Z`),
}));

export const defaultDemoUid = 'demo-alex';
